### ISSUE TITLE
Something about dataset and code

### ISSUE THREAD

**Issue by paradisetww** [liuyiqing2018/predict_Ki-67_from_HE#1]
Dear Yiqing Liu,
       Hello, when can you upload the dataset for training and evaluation and the code for training? We are doing some research about this area and really need these resources. Thanks!

**Comment by liuyiqing2018** [comment]
Thank you for your interest in our research! The dataset for training and evaluation can be downloaded from the following link:
https://pan.baidu.com/s/1q3A-IYYrbP6x7JqKURsX0w  (password: hs95)

**Comment by paradisetww** [comment]
Thanks!

**Comment by martingra** [comment]
Hi! I can't download the dataset, since I am not placed in China and cannot create an account in pan.baidu. Can you please share it in other way? Thanks!

**Comment by liuyiqing2018** [comment]
> Hi! I can't download the dataset, since I am not placed in China and cannot create an account in pan.baidu. Can you please share it in other way? Thanks!

Hi, martingra! The dataset has been uploaded to google drive and can be downloaded from the following link: https://drive.google.com/drive/folders/1rotoQHoAH_m8tJfSiMbL_n3a6xeLviY0?usp=sharing
