### ISSUE TITLE
Reproducing your results

### ISSUE THREAD

**Issue by marioparreno** [liuyiqing2018/predict_Ki-67_from_HE#2]
Hi, thank you for sharing it
I am trying to reproduce your results but I obtain predictions with almost not KI67 positive parts and images mainly blue, like no good resolution
are you sharing with the code the same parameters you used for the paper?
Many thanks!

**Comment by liuyiqing2018** [comment]
Yes, the uploaded code has the same parameters I used for the paper. Did you use the trained model or train from scratch?
